function initializeLanguage() {
  var language = localStorage.getItem('asapop-language');
  if (language == null) {
    language = 'en';
  }
  var element = document.getElementById('language-selector');
  element.value = language;
  updateLanguage(language);
}

function loadLanguage() {
  var language = document.getElementById("language-selector").value;
  localStorage.setItem('asapop-language', language);
  updateLanguage(language);
}

function updateLanguage(language) {
  switch (language) {
    case "de":
      $('.around').text("Etwa");
      $('.country').text("Land");
      $('.csv-file').text("CSV-Datei");
      $('.csv-files').text("CSV-Dateien");
      $('.currency').text("Aktualität");
      $('.date').text("Termin");
      $('.decimal-point').text(",");
      $('.election-type').text("Wahltyp");
      $('.electoral-calendar').text("Wahlkalender");
      $('.european-parliament').text("Europäisches Parlament");
      $('.fieldwork-period').text("Forschungsperiode");
      $('.go-to').text("Gehe nach");
      $('.icalendar-file').text("iCalendar-Datei");
      $('.import-this-calendar-as-an').text("Importieren Sie diesen Kalender als");
      $('.instant-seat-projection').text("Sofortprojektion von Sitze");
      $('.language').text("Sprache");
      $('.latest-opinion-polls').text("Neueste Umfragen");
      $('.main-page').text("Hauptseite");
      $('.most-recent-date').text("Datum der letzten Umfrage");
      $('.no-later-than').text("Spätestens");
      $('.no-later-than-around').text("Spätestens etwa");
      $('.no-opinion-polls').text("Keine Umfragen");
      $('.none').text("Keine");
      $('.number-of-opinion-polls').text("Anzahl Umfragen");
      $('.number-of-opinion-polls-ytd').text("Anzahl Umfragen (year-to-date)");
      $('.number-of-response-scenarios').text("Anzahl Antwortsszenarien");
      $('.number-of-response-scenarios-ytd').text("Anzahl Antwortsszenarien (year-to-date)");
      $('.number-of-result-values').text("Anzahl Ergebniswerte");
      $('.number-of-result-values-ytd').text("Anzahl Ergebniswerte (year-to-date)");
      $('.other').text("Sonstige");
      $('.out-of-date').text("Nicht auf dem neuesten Stand");
      $('.parliament').text("Parlament");
      $('.polling-firm-commissioner').text("Meinungsforschungsinstitut / Auftraggeber(e)");
      $('.polling-firm-not-included').text("Das folgende Meinungsforschungsinstitut ist nicht auf diesen Seiten enthalten");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("enge Verbindungen zu einer politischen Partei");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("folgt nicht die allgemein anerkannte methodische Standardregeln");
      $('.polling-firm-not-included-reason-estimation').text("erstellt Schätzungen, nicht Meinungsumfragen");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(teilweise) finanziert von einer autoritären Regierung");
      $('.polling-firm-not-included-reason-fraud-allegations').text("Betrugsvorwürfe");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("kein Meinungsforschungsinstitut");
      $('.polling-firms-not-included').text("Die folgende Meinungsforschungsinstitute sind nicht auf diesen Seiten enthalten");
      $('.possibly-out-of-date').text("Möglicherweise nicht mehr auf dem neuesten Stand");
      $('.president').text("Präsident");
      $('.privacy-statement').text("[Privacy statement: This website uses your browser’s local store, a technology similar to cookies, to store your language preference between sessions.]");
      $('.probably-out-of-date').text("Wahrscheinlich nicht mehr auf dem neuesten Stand");
      $('.probably-up-to-date').text("Wahrscheinlich auf dem neuesten Stand");
      $('.publication-date').text("Veröffentlichungsdatum");
      $('.qualification-of-currency').text("Qualifizierung der Aktualität");
      $('.statistics').text("Statistiken");
      $('.statistics-page').text("Statistiken");
      $('.thousands-separator').text(".");
      $('.total').text("Total");
      $('.upcoming-elections').text("Künftige Wahlen");
      $('.up-to-date').text("Auf dem neuesten Stand");
      $('.year-to-date').text("year-to-date");
      $('._area_ro').text("Rumänien");
      break;
    case "en":
      $('.around').text("Around");
      $('.country').text("Country");
      $('.csv-file').text("CSV File");
      $('.csv-files').text("CSV Files");
      $('.currency').text("Currency");
      $('.date').text("Date");
      $('.decimal-point').text(".");
      $('.election-type').text("Election Type");
      $('.electoral-calendar').text("Electoral Calendar");
      $('.european-parliament').text("European Parliament");
      $('.fieldwork-period').text("Fieldwork Period");
      $('.go-to').text("Go to");
      $('.icalendar-file').text("iCalendar file");
      $('.import-this-calendar-as-an').text("Import this calendar as an");
      $('.instant-seat-projection').text("Instant seat projection");
      $('.language').text("Language");
      $('.latest-opinion-polls').text("Latest Opinion Polls");
      $('.main-page').text("Main Page");
      $('.most-recent-date').text("Date of Most Recent Opinion Poll");
      $('.no-later-than').text("No later than");
      $('.no-later-than-around').text("No later than around");
      $('.no-opinion-polls').text("No opinion polls");
      $('.none').text("None");
      $('.number-of-opinion-polls').text("Number of Opinion Polls");
      $('.number-of-opinion-polls-ytd').text("Number of Opinion Polls (Year-to-date)");
      $('.number-of-response-scenarios').text("Number of Response Scenarios");
      $('.number-of-response-scenarios-ytd').text("Number of Response Scenarios (Year-to-date)");
      $('.number-of-result-values').text("Number of Result Values");
      $('.number-of-result-values-ytd').text("Number of Result Values (Year-to-date)");
      $('.other').text("Other");
      $('.out-of-date').text("Out of date");
      $('.parliament').text("Parliament");
      $('.polling-firm-commissioner').text("Polling Firm / Commissioner(s)");
      $('.polling-firm-not-included').text("The following polling firm is not included on these pages");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("close ties to a political party");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("doesn’t follow widely accepted standard methodological rules");
      $('.polling-firm-not-included-reason-estimation').text("produces estimations, not opinion polls");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(partially) funded by an authoritarian government");
      $('.polling-firm-not-included-reason-fraud-allegations').text("allegations of fraud");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("not a polling firm");
      $('.polling-firms-not-included').text("The following polling firms are not included on these pages");
      $('.possibly-out-of-date').text("Possibly out of date");
      $('.president').text("President");
      $('.privacy-statement').text("Privacy statement: This website uses your browser’s local store, a technology similar to cookies, to store your language preference between sessions.");
      $('.probably-out-of-date').text("Probably out of date");
      $('.probably-up-to-date').text("Probably up-to-date");
      $('.publication-date').text("Publication date");
      $('.qualification-of-currency').text("Qualification of currency");
      $('.statistics').text("Statistics");
      $('.statistics-page').text("Statistics");
      $('.thousands-separator').text(",");
      $('.total').text("Total");
      $('.upcoming-elections').text("Upcoming Elections");
      $('.up-to-date').text("Up-to-date");
      $('.year-to-date').text("Year-to-date");
      $('._area_ro').text("Romania");
      break;
    case "eo":
      $('.around').text("Ĉirkaŭ");
      $('.country').text("Lando");
      $('.csv-file').text("CSV-dosiero");
      $('.csv-files').text("CSV-dosieroj");
      $('.currency').text("Aktualeco");
      $('.date').text("Dato");
      $('.decimal-point').text(",");
      $('.election-type').text("Balota tipo");
      $('.electoral-calendar').text("Balota kalendaro");
      $('.european-parliament').text("Eŭropa Parlamento");
      $('.fieldwork-period').text("Periodo de esplorado");
      $('.go-to').text("Iru al");
      $('.icalendar-file').text("iCalendar-dosieron");
      $('.import-this-calendar-as-an').text("Importu ĉi tiun kalendaron kiel");
      $('.instant-seat-projection').text("Tujprojekcio de seĝoj");
      $('.language').text("Lingvo");
      $('.latest-opinion-polls').text("Plej novaj opinisondoj");
      $('.main-page').text("Ĉefpaĝo");
      $('.most-recent-date').text("Dato de la plej lasta opinisondo");
      $('.no-later-than').text("Ne pli malfrue ol");
      $('.no-later-than-around').text("Ne pli malfrue ol ĉirkaŭ");
      $('.no-opinion-polls').text("Neniuj opinisondoj");
      $('.none').text("Neniu");
      $('.number-of-opinion-polls').text("Nombro da opinisondoj");
      $('.number-of-opinion-polls-ytd').text("Nombro da opinisondoj (ĝis nun ĉi-jare)");
      $('.number-of-response-scenarios').text("Nombro da respondscenaroj");
      $('.number-of-response-scenarios-ytd').text("Nombro da respondscenaroj (ĝis nun ĉi-jare)");
      $('.number-of-result-values').text("Nombro da rezultvaloroj");
      $('.number-of-result-values-ytd').text("Nombro da rezultvaloroj (ĝis nun ĉi-jare)");
      $('.other').text("Aliaj");
      $('.out-of-date').text("Ne ĝisdataj");
      $('.parliament').text("Parlamento");
      $('.polling-firm-commissioner').text("Enketa agentejo / Kliento(j)");
      $('.polling-firm-not-included').text("La sekva enketa agentejo ne estas inkluzivita sur ĉi tiuj paĝoj");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("proksimaj ligoj al politika partio");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("ne sekvas la vaste akceptitajn normajn metodikajn regulojn");
      $('.polling-firm-not-included-reason-estimation').text("produktas taksojn, ne opinisondojn");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(parte) financita de aŭtoritata registaro");
      $('.polling-firm-not-included-reason-fraud-allegations').text("akuzoj pri fraŭdo");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("ne enketa agentejo");
      $('.polling-firms-not-included').text("La sekvaj enketaj agentejoj ne estas inkluzivitaj sur ĉi tiuj paĝoj");
      $('.possibly-out-of-date').text("Eble ne plu ĝisdataj");
      $('.president').text("Prezidento");
      $('.privacy-statement').text("[Privacy statement: This website uses your browser’s local store, a technology similar to cookies, to store your language preference between sessions.]");
      $('.probably-out-of-date').text("Verŝajne ne plu ĝisdataj");
      $('.probably-up-to-date').text("Verŝajne ĝisdataj");
      $('.publication-date').text("Dato de publikigo");
      $('.qualification-of-currency').text("Kvalifiko de aktualeco");
      $('.statistics').text("Statistikoj");
      $('.statistics-page').text("Statistikoj");
      $('.thousands-separator').text(".");
      $('.total').text("Entute");
      $('.upcoming-elections').text("Venontaj balotoj");
      $('.up-to-date').text("Ĝisdata");
      $('.year-to-date').text("ĝis nun ĉi-jare");
      $('._area_ro').text("Rumanio");
      break;
    case "fr":
      $('.around').text("Environ");
      $('.country').text("Pays");
      $('.csv-file').text("Fichier CSV");
      $('.csv-files').text("Fichiers CSV");
      $('.currency').text("Mise à jour");
      $('.date').text("Date");
      $('.decimal-point').text(",");
      $('.election-type').text("Genre d’élection");
      $('.electoral-calendar').text("Calandrier électoral");
      $('.european-parliament').text("Parlement européen");
      $('.fieldwork-period').text("Période de recherche");
      $('.go-to').text("Aller à");
      $('.icalendar-file').text("fichier iCalendar");
      $('.import-this-calendar-as-an').text("Importez ce calendrier sous forme de");
      $('.instant-seat-projection').text("Projection instantanée en sièges");
      $('.language').text("Langue");
      $('.latest-opinion-polls').text("Derniers sondages");
      $('.main-page').text("Accueil principal");
      $('.most-recent-date').text("Date du sondage le plus récent");
      $('.no-later-than').text("Au plus tard");
      $('.no-later-than-around').text("Au plus tard environ");
      $('.no-opinion-polls').text("Pas de sondages");
      $('.none').text("Aucun");
      $('.number-of-opinion-polls').text("Nombre de sondages");
      $('.number-of-opinion-polls-ytd').text("Nombre de sondages (année à ce jour)");
      $('.number-of-response-scenarios').text("Nombre de scénarios de réponse");
      $('.number-of-response-scenarios-ytd').text("Nombre de scénarios de réponse (année à ce jour)");
      $('.number-of-result-values').text("Nombre de valeurs de résultat");
      $('.number-of-result-values-ytd').text("Nombre de valeurs de résultat (année à ce jour)");
      $('.other').text("Autres");
      $('.out-of-date').text("Pas à jour");
      $('.parliament').text("Parlement");
      $('.polling-firm-commissioner').text("Agence de sondage / Client(s)");
      $('.polling-firm-not-included').text("L’agence de sondage suivante n’est pas incluse dans ces pages");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("des liens étroits avec un parti politique");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("ne suit pas les règles méthodologiques largement acceptées comme standard");
      $('.polling-firm-not-included-reason-estimation').text("produit des estimations, pas des sondages d’opinion");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(partiellement) financé par un gouvernement autoritaire");
      $('.polling-firm-not-included-reason-fraud-allegations').text("allégations de fraude");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("pas une agence de sondage");
      $('.polling-firms-not-included').text("Les agences de sondage suivantes ne sont pas incluses dans ces pages");
      $('.possibly-out-of-date').text("Peut-être pas plus à jour");
      $('.president').text("Président");
      $('.privacy-statement').text("[Privacy statement: This website uses your browser’s local store, a technology similar to cookies, to store your language preference between sessions.]");
      $('.probably-out-of-date').text("Probablement pas plus à jour");
      $('.probably-up-to-date').text("Probablement à jour");
      $('.publication-date').text("Date de publication");
      $('.qualification-of-currency').text("Qualification de mise à jour");
      $('.statistics').text("Statistiques");
      $('.statistics-page').text("Statistiques");
      $('.thousands-separator').text(" ");
      $('.total').text("Total");
      $('.upcoming-elections').text("Prochaines élections");
      $('.up-to-date').text("À jour");
      $('.year-to-date').text("année à ce jour");
      $('._area_ro').text("Roumanie");
      break;
    case "nl":
      $('.around').text("Omtrent");
      $('.country').text("Land");
      $('.csv-file').text("CSV-bestand");
      $('.csv-files').text("CSV-bestanden");
      $('.currency').text("Bijgewerktheid");
      $('.date').text("Datum");
      $('.decimal-point').text(",");
      $('.election-type').text("Soort verkiezing");
      $('.electoral-calendar').text("Verkiezingskalender");
      $('.european-parliament').text("Europees Parlement");
      $('.fieldwork-period').text("Onderzoeksperiode");
      $('.go-to').text("Ga naar");
      $('.icalendar-file').text("iCalendar-bestand");
      $('.import-this-calendar-as-an').text("Importeer deze kalender als een");
      $('.instant-seat-projection').text("Enkelvoudige projectie in zetels");
      $('.language').text("Taal");
      $('.latest-opinion-polls').text("Laatste opiniepeilingen");
      $('.main-page').text("Hoofdpagina");
      $('.most-recent-date').text("Datum van recentste opiniepeiling");
      $('.no-later-than').text("Niet later dan");
      $('.no-later-than-around').text("Niet later dan omtrent");
      $('.no-opinion-polls').text("Geen opiniepeilingen");
      $('.none').text("Geen");
      $('.number-of-opinion-polls').text("Aantal opiniepeilingen");
      $('.number-of-opinion-polls-ytd').text("Aantal opiniepeilingen (year-to-date)");
      $('.number-of-response-scenarios').text("Aantal responsscenario’s");
      $('.number-of-response-scenarios-ytd').text("Aantal responsscenario’s (year-to-date)");
      $('.number-of-result-values').text("Aantal resultaatwaarden");
      $('.number-of-result-values-ytd').text("Aantal resultaatwaarden (year-to-date)");
      $('.other').text("Anderen");
      $('.out-of-date').text("Niet meer up-to-date");
      $('.parliament').text("Parlement");
      $('.polling-firm-commissioner').text("Peilingsbureau / Opdrachtgever(s)");
      $('.polling-firm-not-included').text("Het volgende peilingsbureau is niet opgenomen in deze pagina’s");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("nauwe banden met een politieke partij");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("volgt niet de algemeen aanvaarde standaardmethodologische regels");
      $('.polling-firm-not-included-reason-estimation').text("produceert schattingen, geen opiniepeilingen");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(gedeeltelijk) gefinancierd door een autoritaire regering");
      $('.polling-firm-not-included-reason-fraud-allegations').text("beschuldigingen van fraude");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("geen peilingsbureau");
      $('.polling-firms-not-included').text("De volgende peilingsbureaus zijn niet opgenomen in deze pagina’s");
      $('.possibly-out-of-date').text("Mogelijk niet meer up-to-date");
      $('.president').text("President");
      $('.privacy-statement').text("Verklaring over de bescherming van persoonsgegevens: Deze website gebruikt de local store van je browser, een technologie vergelijkbaar met cookies, om tussen twee sessies in je taalkeuze te kunnen bewaren.");
      $('.probably-out-of-date').text("Waarschijnlijk niet meer up-to-date");
      $('.probably-up-to-date').text("Waarschijnlijk up-to-date");
      $('.publication-date').text("Publicatiedatum");
      $('.qualification-of-currency').text("Kwalificatie van de bijgewerktheid");
      $('.statistics').text("Statistieken");
      $('.statistics-page').text("Statistieken");
      $('.thousands-separator').text(".");
      $('.total').text("Totaal");
      $('.upcoming-elections').text("Komende verkiezingen");
      $('.up-to-date').text("Up-to-date");
      $('.year-to-date').text("year-to-date");
      $('._area_ro').text("Roemenië");
      break;
    case "no":
      $('.around').text("Omtrent");
      $('.country').text("Land");
      $('.csv-file').text("CSV-fil");
      $('.csv-files').text("CSV-filer");
      $('.currency').text("Oppdaterthet");
      $('.date').text("Dato");
      $('.decimal-point').text(",");
      $('.election-type').text("Valgtype");
      $('.electoral-calendar').text("Valgkalender");
      $('.european-parliament').text("Europaparlamentet");
      $('.fieldwork-period').text("Undersøkelsesperiode");
      $('.go-to').text("Gå til");
      $('.icalendar-file').text("iCalendar-fil");
      $('.import-this-calendar-as-an').text("Importer denne kalenderen som en");
      $('.instant-seat-projection').text("Direkteprojeksjon til mandater");
      $('.language').text("Språk");
      $('.latest-opinion-polls').text("Siste meningsmålinger");
      $('.main-page').text("Forside");
      $('.most-recent-date').text("Dato for siste meningsmåling");
      $('.no-later-than').text("Senest");
      $('.no-later-than-around').text("Senest omtrent");
      $('.no-opinion-polls').text("Ingen meningsmålinger");
      $('.none').text("Ingen");
      $('.number-of-opinion-polls').text("Antall meningsmålinger");
      $('.number-of-opinion-polls-ytd').text("Antall meningsmålinger (hittil i år)");
      $('.number-of-response-scenarios').text("Antall responsscenarier");
      $('.number-of-response-scenarios-ytd').text("Antall responsscenarier (hittil i år)");
      $('.number-of-result-values').text("Antall resultatverdier");
      $('.number-of-result-values-ytd').text("Antall resultatverdier (hittil i år)");
      $('.other').text("Andre");
      $('.out-of-date').text("Utdatert");
      $('.parliament').text("Parlament");
      $('.polling-firm-commissioner').text("Meningsmålingsinstitutt / Oppdragsgiver(e)");
      $('.polling-firm-not-included').text("Følgende meningsmålingsinstitutt er ikke tatt med på disse sider");
      $('.polling-firm-not-included-reason-close-ties-to-a-political-party').text("nære bånd til et politisk parti");
      $('.polling-firm-not-included-reason-does-not-follow-standard-methodological-rules').text("følger ikke de allment aksepterte standard metodologiske reglene");
      $('.polling-firm-not-included-reason-estimation').text("produserer estimater, ikke meningsmålinger");
      $('.polling-firm-not-included-reason-funded-by-an-authoritarian-government').text("(delvis) finansiert av en autoritær regjering");
      $('.polling-firm-not-included-reason-fraud-allegations').text("anklager om svindel");
      $('.polling-firm-not-included-reason-not-a-polling-firm').text("ikke et meningsmålingsinstitutt");
      $('.polling-firms-not-included').text("Følgende meningsmålingsinstitutter er ikke tatt med på disse sider");
      $('.possibly-out-of-date').text("Muligens utdatert");
      $('.president').text("President");
      $('.privacy-statement').text("[Privacy statement: This website uses your browser’s local store, a technology similar to cookies, to store your language preference between sessions.]");
      $('.probably-out-of-date').text("Sannsynligvis utdatert");
      $('.probably-up-to-date').text("Sannsynligvis oppdatert");
      $('.publication-date').text("Publiseringsdato");
      $('.qualification-of-currency').text("Kvalifisering av oppdaterthet");
      $('.statistics').text("Statistikkene");
      $('.statistics-page').text("Statistikkene");
      $('.thousands-separator').text(" ");
      $('.total').text("Total");
      $('.upcoming-elections').text("Kommende valg");
      $('.up-to-date').text("Oppdatert");
      $('.year-to-date').text("hittil i år");
      $('._area_ro').text("Romania");
      break;
  }
}
